services:
  redis:
    image: "redis:7.4"
    restart: "on-failure:3"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:16.4"
    restart: "on-failure:3"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  kafka:
    image: "bitnami/kafka:3.9"
    restart: "on-failure:3"
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@localhost:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
