// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDevice = `-- name: GetDevice :one
SELECT device_id, source, external_device_id, metadata, inserted_at, updated_at FROM devices WHERE device_id = $1
`

func (q *Queries) GetDevice(ctx context.Context, deviceID pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.Source,
		&i.ExternalDeviceID,
		&i.Metadata,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT session_id, device_id, ends_at, inserted_at, updated_at FROM sessions WHERE session_id = $1
`

func (q *Queries) GetSession(ctx context.Context, sessionID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.DeviceID,
		&i.EndsAt,
		&i.InsertedAt,
		&i.UpdatedAt,
	)
	return i, err
}
