CREATE TABLE IF NOT EXISTS devices (
  device_id UUID PRIMARY KEY,
  source TEXT NOT NULL,
  external_device_id UUID NOT NULL UNIQUE,
  metadata JSONB NOT NULL,
  inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
  session_id UUID PRIMARY KEY,
  device_id UUID NOT NULL REFERENCES devices(device_id),
  ends_at TIMESTAMP NOT NULL,
  inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
