// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DeviceID         pgtype.UUID
	Source           string
	ExternalDeviceID pgtype.UUID
	Metadata         []byte
	InsertedAt       pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Session struct {
	SessionID  pgtype.UUID
	DeviceID   pgtype.UUID
	EndsAt     pgtype.Timestamp
	InsertedAt pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
